# Generated by Django 5.1.3 on 2024-11-30 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_church', related_query_name='city', to='church.city'),
        ),
        migrations.AddField(
            model_name='church',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_church', related_query_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='church',
            name='leader2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader2_church', related_query_name='leader2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='church',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_church', related_query_name='type', to='church.church_type'),
        ),
    ]
