# Generated by Django 5.1.3 on 2024-12-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_church', related_query_name='city', to='church.city'),
        ),
        migrations.AlterField(
            model_name='church',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_church', related_query_name='type', to='church.church_type'),
        ),
    ]
