# Generated by Django 5.1.3 on 2024-12-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_church_city_church_leader_church_leader2_church_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'default_permissions': (), 'verbose_name': 'Church', 'verbose_name_plural': 'Churches'},
        ),
        migrations.AlterModelOptions(
            name='church_type',
            options={'default_permissions': (), 'verbose_name': 'Church_type', 'verbose_name_plural': 'Church_types'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
