"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("DJANGO_ENV") == "development" else False


# Application definition

SHARED_APPS = [
    "django_tenants",
    "tenants",
    "django.contrib.contenttypes",
    "django_dramatiq",
]

TENANT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_crontab",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "auth_custom",
    "members",
    "admin_custom",
    "church",
    "event",
    "dashboard",
    "department",
    "finance",
    "communication",
    "seeders",
    "attendance",
    "device",
    "storages",
    "multimedia",
    "internal"
]

INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]


REST_FRAMEWORK = {
   'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/min',
        'user': '120/min',
        'login': '5/min',
        'pwreset': '3/min',
    },
    # YOUR SETTINGS
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "auth_custom.auth.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "auth_custom.auth.CustomPermissions",
    ],
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

APPEND_SLASH = False


SPECTACULAR_SETTINGS = {
    "TITLE": "Ecclesix API",
    "DESCRIPTION": "Church management system API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # OTHER SETTINGS
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    # OTHER SETTINGS
}


MIDDLEWARE = [
    "backend.middleware.MetricsAwareTenantMainMiddleware",
    "backend.middleware.PrometheusMetricsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "backend.middleware.InternalAPIMiddleware",
    "backend.middleware.RequestLoggingMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if os.getenv("CORS_ALLOWED_ORIGINS") else []
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if os.getenv("CSRF_TRUSTED_ORIGINS") else []

PROMETHEUS_METRICS_PATH = os.getenv("PROMETHEUS_METRICS_PATH", "/metrics")
PROMETHEUS_TENANT_LABEL_MODE = os.getenv("PROMETHEUS_TENANT_LABEL_MODE", "grouped")
PROMETHEUS_TENANT_LABEL_ALLOWLIST = [
    item.strip()
    for item in os.getenv("PROMETHEUS_TENANT_LABEL_ALLOWLIST", "").split(",")
    if item.strip()
]

# Secret for internal API requests (used by `backend.middleware.InternalAPIMiddleware`)
# Set this in your environment as `INTERNAL_API_SECRET`.
INTERNAL_API_SECRET = os.getenv("INTERNAL_API_SECRET", "")

# Prometheus URL for metrics queries (used by `internal.views_infra_stats`)
# Set this in your environment as `PROMETHEUS_URL` (defaults to http://localhost:9090)
PROMETHEUS_URL = os.getenv("PROMETHEUS_URL", "http://localhost:9090")

REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "ecclesix",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ecclesix-tenant-cache",
        }
    }


ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        "OPTIONS": {"sslmode": os.getenv("DB_SSLMODE", "prefer")},
    }
}

DATABASE_ROUTERS = ["django_tenants.routers.TenantSyncRouter"]
TENANT_MODEL = "tenants.Tenant"
TENANT_DOMAIN_MODEL = "tenants.TenantDomain"



EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
    if os.getenv("DJANGO_ENV") == "development"
    else "anymail.backends.resend.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True if os.getenv("DJANGO_ENV") == "production" else False


ANYMAIL = {
    "RESEND_API_KEY": os.getenv("RESEND_API_KEY"),
}

DEFAULT_FROM_EMAIL = "Ecclesix <support@ecclesix.com>"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr-FR"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


AUTH_USER_MODEL = "members.Member"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/dist/assets'),
    os.path.join(BASE_DIR, 'frontend/dist'), 
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

TEMPLATES[0]['DIRS'].append(os.path.join(BASE_DIR, 'frontend/dist'))

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
LOG_SERVICE_NAME = os.getenv("LOG_SERVICE_NAME", "ecclesix-api")
LOG_TO_FILE = os.getenv("LOG_TO_FILE", "false").lower() == "true"
LOG_DIR = Path(os.getenv("LOG_DIR", BASE_DIR / "logs"))
LOG_FILE_PATH = LOG_DIR / os.getenv("LOG_FILE_NAME", "app.json.log")

LOG_HANDLERS = {
    # "console": {
    #     "class": "logging.StreamHandler",
    #     "stream": "ext://sys.stdout",
    #     "formatter": "json",
    #     "filters": ["request_context"],
    # }
}

if LOG_TO_FILE:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    LOG_HANDLERS["file"] = {
        "class": "logging.handlers.TimedRotatingFileHandler",
        "filename": str(LOG_FILE_PATH),
        "when": "midnight",
        "backupCount": 14,
        "encoding": "utf-8",
        "formatter": "json",
        "filters": ["request_context"],
    }

DEFAULT_LOG_HANDLERS = list(LOG_HANDLERS.keys())

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "backend.logging_utils.RequestContextFilter",
        }
    },
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s %(service)s %(environment)s %(request_id)s %(tenant)s %(user_id)s %(remote_addr)s %(method)s %(path)s %(status_code)s %(duration_ms)s %(pathname)s %(lineno)d",
        },
    },
    "handlers": LOG_HANDLERS,
    "root": {
        "level": LOG_LEVEL,
        "handlers": DEFAULT_LOG_HANDLERS,
    },
}

# Run tenant-aware jobs on all church schemas.
CRONTAB_PYTHON_EXECUTABLE = sys.executable.replace(" ", r"\ ")
CRONTAB_DJANGO_MANAGE_PATH = str(BASE_DIR / "manage.py").replace(" ", r"\ ")
CRONJOBS = [
    (
        "0 0 1 * *",
        "django.core.management.call_command",
        ["run_command_for_all_tenants", "monthly_balance_job"],
    ),
    # Run visitor to member conversion job daily at 2 AM for all tenants
    (
        "0 2 * * *",
        "django.core.management.call_command",
        ["run_command_for_all_tenants", "visitor_to_member_job"],
    ),
    # Run active to inactive conversion job daily at 2:30 AM for all tenants
    (
        "30 2 * * *",
        "django.core.management.call_command",
        ["run_command_for_all_tenants", "active_to_inactive_job"],
    ),
]

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
   
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        "OPTIONS": {
            "location": "staticfiles",
        },
    },
}

# DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = "private"
AWS_QUERYSTRING_AUTH = True
AWS_S3_ADDRESSING_STYLE = "path"




INTERNAL_API_SECRET_ADMIN = os.getenv("INTERNAL_API_SECRET_ADMIN", "admin-secret-key")
INTERNAL_API_SECRET_MOD = os.getenv("INTERNAL_API_SECRET_MOD", "mod-secret-key")








DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.redis.RedisBroker", 
    "OPTIONS": {
        "url": REDIS_URL,
    },
    "MIDDLEWARE": [
        "dramatiq.middleware.prometheus.Prometheus",
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
        "django_dramatiq.middleware.AdminMiddleware",
    ]
}