# Generated by Django 5.1.3 on 2024-12-18 18:15

import django.core.validators
import django.db.models.deletion
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0004_alter_church_leader_alter_church_leader2'),
        ('event', '0004_alter_event_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=70)),
                ('category_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Budget', 'Budget')], max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('Caisse', 'Caisse'), ('Bancaire', 'Bancaire')], max_length=10)),
                ('balance', finance.models.EncryptedField(max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=50, verbose_name='Budget Name')),
                ('allocated_amount', finance.models.EncryptedField(max_length=100)),
                ('total_amount', finance.models.EncryptedField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='Budget Category')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'permissions': [('ajouter_budget', 'Ajouter Budget')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Monthly_Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.SmallIntegerField()),
                ('year', models.SmallIntegerField()),
                ('balance', finance.models.EncryptedField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
            ],
            options={
                'verbose_name': 'Monthly_Balance',
                'verbose_name_plural': 'Monthly_Balances',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('amount', finance.models.EncryptedField(max_length=100, verbose_name='Amount')),
                ('status', models.CharField(choices=[('Validated', 'Validated'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=50, verbose_name='Status')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Transfer', 'Transfer')], max_length=50, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budget')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='finance.account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'permissions': [('voir_finance', 'Voir Finance'), ('voir_toutes_finances', 'Voir Toutes Finances'), ('ajouter_transaction', 'Ajouter Transaction'), ('confirmer_transaction', 'Confirmer Transaction')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transaction_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Modified', 'Modified'), ('Deleted', 'Deleted'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], max_length=50, verbose_name='Action')),
                ('transaction_no', models.IntegerField(verbose_name='Transaction No')),
                ('previous_state', models.JSONField()),
                ('new_state', models.JSONField()),
                ('comment', models.CharField(max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction_Log',
                'verbose_name_plural': 'Transaction_Logs',
                'permissions': [('voir_financelog', 'Voir Finance Log')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transaction_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
            ],
            options={
                'verbose_name': 'transaction_rule',
                'verbose_name_plural': 'transactions_rules',
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gte', 0.0), ('percentage__lte', 100.0)), name='check_percentage')],
                'unique_together': {('account', 'category', 'church')},
            },
        ),
    ]
