# Generated by Django 5.1.3 on 2024-12-16 23:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0004_alter_church_leader_alter_church_leader2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=70)),
                ('category_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Budget', 'Budget')], max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('Caisse', 'Caisse'), ('Bancaire', 'Bancaire')], max_length=10)),
                ('amount', models.CharField(max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transaction_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
            ],
            options={
                'verbose_name': 'transaction_rule',
                'verbose_name_plural': 'transactions_rules',
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='check_percentage')],
                'unique_together': {('account', 'category', 'church')},
            },
        ),
    ]
