# Generated by Django 5.1.3 on 2024-12-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_log',
            name='new_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_log',
            name='previous_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
