# Generated by Django 5.1.3 on 2024-12-20 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_alter_church_leader_alter_church_leader2'),
        ('finance', '0002_alter_transaction_log_new_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.church'),
        ),
        migrations.AlterField(
            model_name='transaction_log',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
    ]
