# Generated by Django 5.1.3 on 2024-12-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_account_church_alter_transaction_log_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='total_amount',
            new_name='actual_amount',
        ),
    ]
