# Generated by Django 5.1.3 on 2024-12-20 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_total_amount_budget_actual_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_log',
            old_name='new_state',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='transaction_log',
            name='previous_state',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.transaction'),
        ),
    ]
