# Generated by Django 5.1.3 on 2024-12-20 15:32

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_new_state_transaction_log_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='actual_amount',
            field=finance.models.EncryptedField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='details',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
