# Generated by Django 5.1.3 on 2024-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_budget_actual_amount_alter_budget_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
