# Generated by Django 5.1.3 on 2026-04-17 06:44

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.SlugField(max_length=80, unique=True)),
                ('church_name', models.CharField(max_length=150)),
                ('domain', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain without protocol, path, or port.', regex='^(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['church_name'],
                'indexes': [models.Index(fields=['domain', 'is_active'], name='tenants_ten_domain_dcca91_idx'), models.Index(fields=['name', 'is_active'], name='tenants_ten_name_64e0af_idx'), models.Index(fields=['schema_name'], name='tenants_ten_schema__df93bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'ordering': ['domain'],
                'indexes': [models.Index(fields=['domain', 'is_active'], name='tenants_ten_domain_1eabe2_idx')],
            },
        ),
    ]
