# Generated by Django 5.1.3 on 2026-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_providerinformation_tenant_email_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinformation',
            name='provider_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
