# Generated by Django 5.1.3 on 2026-04-21 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_providerinformation_provider_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantStorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_bytes', models.BigIntegerField(default=5368709120)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
