# Generated by Django 5.1.3 on 2026-04-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantstoragequota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingplan',
            options={'default_permissions': (), 'ordering': ['price', 'name']},
        ),
        migrations.AlterModelOptions(
            name='providerinformation',
            options={'default_permissions': (), 'ordering': ['provider_name']},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'default_permissions': (), 'ordering': ['church_name']},
        ),
        migrations.AlterModelOptions(
            name='tenantdomain',
            options={'default_permissions': (), 'ordering': ['domain']},
        ),
        migrations.AlterModelOptions(
            name='tenantpaymenthistory',
            options={'default_permissions': (), 'ordering': ['-paid_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tenantstoragequota',
            options={'default_permissions': (), 'verbose_name': 'tenant storage quota', 'verbose_name_plural': 'tenant storage quotas'},
        ),
        migrations.AddIndex(
            model_name='providerinformation',
            index=models.Index(fields=['provider_name'], name='tenants_pro_provide_f0be19_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantstoragequota',
            index=models.Index(fields=['tenant'], name='tenants_ten_tenant__4fd122_idx'),
        ),
    ]
