# Generated by Django 5.1.3 on 2026-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_billingplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('all', 'All Tenants'), ('specific', 'Specific Tenants')], default='all', max_length=20)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('target_tenants', models.ManyToManyField(blank=True, help_text="Leave empty if visibility is 'all'", related_name='public_announcements', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['status', 'visibility'], name='tenants_pub_status_ee0c1c_idx'), models.Index(fields=['-published_at'], name='tenants_pub_publish_d4bd8b_idx')],
            },
        ),
    ]
