# Generated by Django 5.1.3 on 2026-04-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_publicannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='max_churches',
            field=models.IntegerField(default=1, help_text='Maximum number of churches allowed'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='max_members',
            field=models.IntegerField(default=100, help_text='Maximum number of members allowed'),
        ),
    ]
