# Generated by Django 5.1.3 on 2026-05-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_billingplan_max_churches_billingplan_max_members'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenants_ten_domain_dcca91_idx',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='custom_domain',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='custom_domain_verified',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='domain',
        ),
        migrations.AddField(
            model_name='tenant',
            name='church_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
