# Generated by Django 5.1.3 on 2026-05-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_remove_tenant_tenants_ten_domain_dcca91_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='annual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
