# Generated by Django 5.1.3 on 2026-04-21 23:20

import django.db.models.deletion
import multimedia.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0004_servicereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Vidéo'), ('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('file', models.FileField(storage=multimedia.storage.TenantMediaStorage(), upload_to='')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='event.event')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
