# Generated by Django 5.1.3 on 2026-04-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'default_permissions': (), 'permissions': [('ajouter_mediafile', 'Ajouter MediaFile'), ('voir_mediafile', 'Voir MediaFile'), ('supprimer_mediafile', 'Supprimer MediaFile')], 'verbose_name': 'media file', 'verbose_name_plural': 'media files'},
        ),
    ]
