# Generated by Django 5.1.3 on 2026-04-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_initial'),
        ('multimedia', '0003_alter_mediafile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='church.church'),
        ),
    ]
