# Generated by Django 5.1.3 on 2026-04-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_servicereport_options'),
        ('multimedia', '0004_mediafile_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='event.event'),
        ),
    ]
