# Generated by Django 5.1.3 on 2026-05-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0006_mediafile_scan_result_mediafile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='object_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
