# Generated by Django 5.1.3 on 2026-06-03 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_initial'),
        ('event', '0005_alter_servicereport_options'),
        ('multimedia', '0007_mediafile_object_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Vidéo'), ('image', 'Image'), ('document', 'Document')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['church', 'media_type'], name='multimedia__church__fd9bde_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['-uploaded_at'], name='multimedia__uploade_4a5546_idx'),
        ),
    ]
