# Generated by Django 5.1.3 on 2026-04-17 06:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_stats',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('event_type_name', models.CharField(max_length=50)),
                ('month', models.PositiveSmallIntegerField(verbose_name='month')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('church_id', models.IntegerField(verbose_name='church')),
                ('totals', models.IntegerField(verbose_name='total')),
                ('average', models.IntegerField(verbose_name='average')),
            ],
            options={
                'verbose_name': 'event_stat',
                'verbose_name_plural': 'event_stats',
                'db_table': 'events_stats',
                'ordering': ['year', 'month', 'church_id', 'event_type_name'],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=50, unique=True, verbose_name='event type name')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('weekly_event', models.BooleanField(default=False, verbose_name='weekly event')),
                ('event_day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, verbose_name='event day of week')),
            ],
            options={
                'verbose_name': 'event_type',
                'verbose_name_plural': 'event_types',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='event name')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('men', models.IntegerField(default=0, verbose_name='men')),
                ('women', models.IntegerField(default=0, verbose_name='women')),
                ('children', models.IntegerField(default=0, verbose_name='children')),
                ('total', models.IntegerField(default=0, verbose_name='total')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event_type')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'permissions': [('ajouter_evenement', 'Ajouter Evenement'), ('modifier_evenement', 'Modifier Evenement'), ('voir_evenement', 'Voir Evenement'), ('voir_touts_evenements', 'Voir Touts Les Evenements'), ('supprimer_evenement', 'Supprimer Evenement')],
                'default_permissions': (),
                'unique_together': {('event_date', 'event_type', 'church')},
            },
        ),
    ]
