# Generated by Django 5.1.3 on 2024-12-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=50, verbose_name='month')),
                ('year', models.CharField(max_length=50, verbose_name='year')),
                ('church_id', models.CharField(max_length=50, verbose_name='church')),
                ('totals', models.CharField(max_length=50, verbose_name='total')),
                ('average', models.CharField(max_length=50, verbose_name='average')),
            ],
            options={
                'verbose_name': 'event_stat',
                'verbose_name_plural': 'event_stats',
                'db_table': 'events_stats',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=50, unique=True, verbose_name='event type name')),
                ('weekly_event', models.BooleanField(default=False, verbose_name='weekly event')),
            ],
            options={
                'verbose_name': 'event_type',
                'verbose_name_plural': 'event_types',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='event name')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('men', models.IntegerField(default=0, verbose_name='men')),
                ('women', models.IntegerField(default=0, verbose_name='women')),
                ('children', models.IntegerField(default=0, verbose_name='children')),
                ('total', models.IntegerField(verbose_name='total')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event_type')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'permissions': [('ajouter_evenement', 'Ajouter Evenement'), ('modifier_evenement', 'Modifier Evenement'), ('voir_evenement', 'Voir Evenement'), ('voir_touts_evenements', 'Voir Touts Les Evenements'), ('supprimer_evenement', 'Supprimer Evenement')],
                'default_permissions': (),
                'unique_together': {('event_date', 'event_type', 'church')},
            },
        ),
    ]
