# Generated by Django 5.1.3 on 2024-12-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0003_alter_church_options_alter_church_type_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=50, unique=True, verbose_name='event type name')),
                ('weekly_event', models.BooleanField(default=False, verbose_name='weekly event')),
            ],
            options={
                'verbose_name': 'event_type',
                'verbose_name_plural': 'event_types',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='event name')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('men', models.IntegerField(default=0, verbose_name='men')),
                ('women', models.IntegerField(default=0, verbose_name='women')),
                ('children', models.IntegerField(default=0, verbose_name='children')),
                ('total', models.IntegerField(verbose_name='total')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'default_permissions': (),
                'unique_together': {('event_date', 'event_type', 'church')},
            },
        ),
    ]
