# Generated by Django 5.1.3 on 2024-12-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventType',
            new_name='Event_Type',
        ),
    ]
