# Generated by Django 5.1.3 on 2024-12-15 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 18, 32, 41, 732280, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='total',
            field=models.IntegerField(default=0, verbose_name='total'),
        ),
    ]
