# Generated by Django 5.1.3 on 2026-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_initial'),
        ('event', '0002_auto_20260417_0647'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['church', 'event_date'], name='event_event_church__e9b4b1_idx'),
        ),
    ]
