# Generated by Django 5.1.3 on 2024-12-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_eventtype_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=50, verbose_name='month')),
                ('year', models.CharField(max_length=50, verbose_name='year')),
                ('church_id', models.CharField(max_length=50, verbose_name='church')),
                ('totals', models.CharField(max_length=50, verbose_name='total')),
                ('average', models.CharField(max_length=50, verbose_name='average')),
            ],
            options={
                'verbose_name': 'event_stat',
                'verbose_name_plural': 'event_stats',
                'db_table': 'events_stats',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
