# Generated by Django 5.1.3 on 2026-04-21 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_event_event_church__e9b4b1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preacher', models.CharField(max_length=255)),
                ('sermon_theme', models.CharField(max_length=255)),
                ('bible_reference', models.CharField(blank=True, max_length=100)),
                ('sermon_summary', models.TextField(blank=True)),
                ('after_service_activities', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
