# Generated by Django 5.1.3 on 2026-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_type',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='event_type',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
