# Generated by Django 5.1.3 on 2026-04-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_servicereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereport',
            options={'default_permissions': (), 'verbose_name': 'service_report', 'verbose_name_plural': 'service_reports'},
        ),
    ]
