# Generated by Django 5.1.3 on 2026-04-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_type_end_time_event_type_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_type',
            name='event_day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='event day of week'),
        ),
    ]
