# Generated by Django 5.1.3 on 2026-04-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_type_event_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_type',
            name='event_day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, verbose_name='event day of week'),
        ),
    ]
