# Generated by Django 5.1.3 on 2026-04-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('app_version', models.CharField(max_length=50)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'default_permissions': (),
            },
        ),
    ]
