# Generated by Django 5.1.3 on 2026-09-24 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('all', 'All Churches'), ('specific', 'Specific Churches')], default='all', max_length=20)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_announcements_created', to=settings.AUTH_USER_MODEL)),
                ('target_churches', models.ManyToManyField(blank=True, help_text="Leave empty if visibility is 'all'", related_name='announcements', to='church.church')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'default_permissions': (),
                'indexes': [models.Index(fields=['status', 'visibility'], name='communicati_status_199d1c_idx'), models.Index(fields=['-published_at'], name='communicati_publish_402b83_idx')],
            },
        ),
    ]
