# Generated by Django 5.1.3 on 2026-04-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('envoyer_communication', 'Envoyer Communication'), ('envoyer_toutes_communications', 'Envoyer Toutes Communications')]},
        ),
    ]
