# Generated by Django 5.1.3 on 2026-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_campaign_campaignrecipient_providerconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconfig',
            name='name',
            field=models.CharField(default='kd', help_text='Friendly name for this configuration', max_length=255),
            preserve_default=False,
        ),
    ]
