# Generated by Django 5.1.3 on 2024-11-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_members_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='user_permissions',
        ),
    ]
