# Generated by Django 5.1.3 on 2024-11-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_permissions_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='permission_ptr',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
