# Generated by Django 5.1.3 on 2026-04-17 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True)),
                ('config_value', models.JSONField(blank=True, null=True, verbose_name='config value')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'app config',
                'verbose_name_plural': 'app configs',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=50)),
                ('detail', models.JSONField(verbose_name='details')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='action_time')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'permissions': [('voir_adminlog', 'Voir Admin Log')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'default_permissions': (),
            },
        ),
    ]
