# Generated by Django 5.1.3 on 2024-12-11 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0002_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='time',
        ),
        migrations.AddField(
            model_name='log',
            name='action_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='action_time'),
        ),
    ]
