# Generated by Django 5.1.3 on 2024-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0003_remove_log_time_log_action_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
