# Generated by Django 5.1.3 on 2026-04-02 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0004_role_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True)),
                ('config_value', models.JSONField(blank=True, null=True, verbose_name='config value')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'app config',
                'verbose_name_plural': 'app configs',
                'default_permissions': (),
            },
        ),
    ]
