# Generated by Django 5.1.3 on 2024-11-26 13:56

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_admin', models.BooleanField(default=False)),
                ('device_id', models.CharField(max_length=100)),
                ('otp_key', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('profession_type', models.CharField(choices=[('Travailleur', 'Travailleur'), ('Entrepreneur', 'Entrepreneur'), ('Eleve/Etudiant', 'Eleve/Etudiant'), ('Autres', 'Autres')], max_length=20)),
                ('profession', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
                ('baptism_date', models.DateField()),
                ('marital_status', models.CharField(choices=[('M', 'Marie'), ('C', 'Celibataire'), ('V', 'Veuf')], max_length=10)),
                ('category', models.CharField(choices=[('Ecodim', 'Ecodim'), ('Jeunesse', 'Jeunesse'), ('Adulte', 'Adulte')], max_length=20)),
                ('status', models.CharField(choices=[('Ministre', 'Ministre'), ('Ouvrier', 'Ouvrier'), ('Membre', 'Membre'), ('Visiteur', 'Visiteur')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'members',
                'verbose_name_plural': 'members',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
