# Generated by Django 5.1.3 on 2024-12-09 16:15

import django.db.models.deletion
import django.utils.timezone
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_custom', '0001_initial'),
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_admin', models.BooleanField(default=False)),
                ('device_id', models.CharField(max_length=100, null=True)),
                ('otp_key', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('profession_type', models.CharField(choices=[('Travailleur', 'Travailleur'), ('Entrepreneur', 'Entrepreneur'), ('Eleve/Etudiant', 'Eleve/Etudiant'), ('Autres', 'Autres')], default='Autres', max_length=20)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('M', 'Marie'), ('C', 'Celibataire'), ('V', 'Veuf')], max_length=10)),
                ('category', models.CharField(choices=[('Ecodim', 'Ecodim'), ('Jeunesse', 'Jeunesse'), ('Adulte', 'Adulte')], max_length=20)),
                ('status', models.CharField(choices=[('Ministre', 'Ministre'), ('Ouvrier', 'Ouvrier'), ('Membre', 'Membre'), ('Visiteur', 'Visiteur')], max_length=20)),
                ('church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_member', related_query_name='church', to='church.church')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_member', related_query_name='city', to='church.city')),
                ('followed_up_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_followed_up', to=settings.AUTH_USER_MODEL, verbose_name='followed_up_by')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_member', related_query_name='role', to='admin_custom.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'permissions': [('ajouter_membre', 'Ajouter Membre'), ('modifier_membre', 'Modifier Membre'), ('voir_membre', 'Voir Membre'), ('voir_touts_membres', 'Voir Touts Les Membres')],
                'default_permissions': (),
            },
            managers=[
                ('objects', members.models.UserManagerCustom()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Marriage', 'Marriage'), ('Enfant', 'Enfant'), ('Parent', 'Parent'), ('Frere/Soeur', 'Frere/Soeur'), ('Autres', 'Autres')], max_length=20)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_member_relations', to=settings.AUTH_USER_MODEL)),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_member_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'default_permissions': (),
                'unique_together': {('from_member', 'to_member')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='relations',
            field=models.ManyToManyField(related_name='related_to', through='members.Relationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('email', 'first_name', 'last_name')},
        ),
    ]
