# Generated by Django 5.1.3 on 2026-04-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0002_initial'),
        ('church', '0002_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Ministre', 'Ministre'), ('Ouvrier', 'Ouvrier'), ('Membre', 'Membre'), ('Visiteur', 'Visiteur')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'is_active'], name='members_mem_church__53e067_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'status'], name='members_mem_church__a10b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['church', 'gender'], name='members_mem_church__7236a6_idx'),
        ),
    ]
