# Generated by Django 5.1.3 on 2024-11-26 14:41

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='members',
            managers=[
                ('objects', members.models.UserManagerCustom()),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
