# Generated by Django 5.1.3 on 2024-12-12 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='followed_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_followed_up', to=settings.AUTH_USER_MODEL, verbose_name='followed_up_by'),
        ),
    ]
