# Generated by Django 5.1.3 on 2024-11-30 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='followed_up_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='followed_up_by'),
        ),
    ]
