# Generated by Django 5.1.3 on 2024-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_managers_alter_members_baptism_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='verification_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
