# Generated by Django 5.1.3 on 2024-11-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_verification_code_members_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='device_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='otp_key',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
    ]
