# Generated by Django 5.1.3 on 2024-11-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_followed_up_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('email', 'first_name', 'last_name')},
        ),
    ]
