# Generated by Django 5.1.3 on 2024-12-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
