# Generated by Django 5.1.3 on 2026-04-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_secret',
            field=models.CharField(default='done', editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
