# Generated by Django 5.1.3 on 2024-11-30 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Marriage', 'Marriage'), ('Enfant', 'Enfant'), ('Parent', 'Parent'), ('Frere/Soeur', 'Frere/Soeur'), ('Autres', 'Autres')], max_length=20)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_member_relations', to=settings.AUTH_USER_MODEL)),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_member_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='relations',
            field=models.ManyToManyField(related_name='related_to', through='members.Relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
