# Generated by Django 5.1.3 on 2024-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_otp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='otp_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
