# Generated by Django 5.1.3 on 2026-04-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_qr_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='qr_secret',
        ),
    ]
