# Generated by Django 5.1.3 on 2024-11-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_relationship_member_relations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_member', 'to_member')},
        ),
    ]
