# Generated by Django 5.1.3 on 2024-12-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_followed_up_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'default_permissions': (), 'verbose_name': 'Relationship', 'verbose_name_plural': 'Relationships'},
        ),
    ]
