# Generated by Django 5.1.3 on 2024-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_members_otp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='otp_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='profession_type',
            field=models.CharField(choices=[('Travailleur', 'Travailleur'), ('Entrepreneur', 'Entrepreneur'), ('Eleve/Etudiant', 'Eleve/Etudiant'), ('Autres', 'Autres')], default='Autres', max_length=20),
        ),
    ]
