# Generated by Django 5.1.3 on 2024-11-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_members_address_alter_members_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='members',
            table='members',
        ),
    ]
