# Generated by Django 5.1.3 on 2024-11-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_members_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='eglise_id',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
