# Generated by Django 5.1.3 on 2024-11-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_members_eglise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='eglise_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
