# Generated by Django 5.1.3 on 2026-04-01 14:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0004_alter_church_leader_alter_church_leader2'),
        ('event', '0005_event_type_end_time_event_type_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='arrival time')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='church.church')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='event.event_type')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'permissions': [('ajouter_presence', 'Ajouter Presence'), ('modifier_presence', 'Modifier Presence'), ('voir_presence', 'Voir Presence'), ('voir_toutes_presences', 'Voir Toutes Les Presences'), ('supprimer_presence', 'Supprimer Presence')],
                'default_permissions': (),
                'unique_together': {('member', 'event_type', 'date', 'church')},
            },
        ),
    ]
