# Generated by Django 5.1.3 on 2026-04-17 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='arrival time')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'default_permissions': (),
            },
        ),
    ]
