# Generated by Django 5.1.3 on 2026-04-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'default_permissions': (), 'verbose_name': 'attendance', 'verbose_name_plural': 'attendances'},
        ),
    ]
