# Generated by Django 5.1.3 on 2026-04-21 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('church', '0002_initial'),
        ('event', '0003_event_event_event_church__e9b4b1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['church', 'date'], name='attendance__church__76981b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['church', 'event_type', 'date'], name='attendance__church__322ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', 'church', 'date'], name='attendance__member__32410a_idx'),
        ),
    ]
