# Generated by Django 5.1.3 on 2026-04-17 06:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', related_query_name='church_department', to='church.church')),
                ('department_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deps', related_query_name='dep_head', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='departments', related_query_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'permissions': [('ajouter_departement', 'Ajouter Departement'), ('modifier_departement', 'Modifier Departement'), ('voir_departement', 'Voir Departement'), ('voir_touts_departements', 'Voir Touts Les Departements'), ('supprimer_departement', 'Supprimer Departements'), ('chef_departement', 'Chef Departement')],
                'default_permissions': (),
            },
        ),
    ]
